name: native_crypto_android
description: Android implementation of NativeCrypto
version: 0.1.2

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: native_crypto
    platforms:
      android:
        package: fr.pointcheval.native_crypto_android
        pluginClass: NativeCryptoAndroidPlugin
